/**
 * Base configuration for connecting to a llama.cpp OpenAI-compatible endpoint.
 *
 * @example
 * ```ts
 * const config: LlamaCppProviderConfig = {
 *   baseURL: 'http://192.168.1.95:8010/v1',
 *   modelId: 'Qwen/Qwen3.6-35B-A3B',
 *   contextLength: 262144,
 * };
 * ```
 */
export interface LlamaCppProviderConfig {
  /** The base URL of the llama.cpp OpenAI-compatible API endpoint. */
  baseURL: string;
  /** The model identifier to use for requests. */
  modelId: string;
  /** Maximum context length in tokens. Defaults to model-specific values. */
  contextLength?: number;
  /** Request timeout in milliseconds. Defaults to 120000 (2 minutes). */
  timeout?: number;
}

/**
 * Tool call structure matching the OpenAI format returned by llama.cpp.
 */
export interface LlamaCppToolCall {
  /** Unique identifier for the tool call. */
  id: string;
  /** Always `'function'`. */
  type: "function";
  /** The function to invoke. */
  function: {
    /** Function name. */
    name: string;
    /** Function arguments as a JSON-encoded string. */
    arguments: string;
  };
}

/**
 * Separated reasoning and final content from a model response.
 */
export interface LlamaCppReasoningContent {
  /** The model's internal reasoning chain. */
  reasoning: string;
  /** The final response content. */
  content: string;
}

/**
 * A single message in a llama.cpp chat completion response.
 */
export interface LlamaCppMessage {
  /** Message role (`'assistant'`, `'user'`, etc.). */
  role: string;
  /** Message text content, or `null` if the message contains only tool calls. */
  content: string | null;
  /** Optional reasoning content when `enable_thinking` is active. */
  reasoning_content?: string | null;
  /** Optional tool calls generated by the model. */
  tool_calls?: LlamaCppToolCall[];
}

/**
 * Full non-streaming chat completion response from llama.cpp.
 */
export interface LlamaCppChatCompletionResponse {
  /** Unique response identifier. */
  id: string;
  /** Object type, always `'chat.completion'`. */
  object: string;
  /** Unix timestamp of response creation. */
  created: number;
  /** Model that generated the response. */
  model: string;
  /** Completion choices. */
  choices: Array<{
    /** Choice index. */
    index: number;
    /** The assistant's message. */
    message: LlamaCppMessage;
    /** Why generation stopped (`'stop'`, `'tool_calls'`, etc.). */
    finish_reason: string | null;
  }>;
  /** Optional token usage statistics. */
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

/**
 * A single SSE chunk from a streaming llama.cpp response.
 */
export interface LlamaCppStreamChunk {
  /** Unique response identifier. */
  id: string;
  /** Object type, always `'chat.completion.chunk'`. */
  object: string;
  /** Unix timestamp of chunk creation. */
  created: number;
  /** Model that generated the response. */
  model: string;
  /** Delta choices for this chunk. */
  choices: Array<{
    /** Choice index. */
    index: number;
    /** Incremental content delta. */
    delta: {
      role?: string;
      content?: string | null;
      reasoning_content?: string | null;
      tool_calls?: Array<Partial<LlamaCppToolCall>>;
    };
    /** Why generation stopped, or `null` while streaming. */
    finish_reason: string | null;
  }>;
}

/**
 * Supported Qwen3.6 model identifiers.
 *
 * - `'Qwen/Qwen3.6-35B-A3B'` — Full multimodal model (vision + reasoning + tool calls).
 * - `'Qwen/Qwen3.6-27B'` — Text-only model (no vision due to `--no-mmproj`).
 */
export type Qwen36ModelId = "Qwen/Qwen3.6-35B-A3B" | "Qwen/Qwen3.6-27B";

/**
 * The Gemma4 model identifier used by the Gemma4 provider.
 */
export type Gemma4ModelId = "TrevorJS/gemma-4-26B-A4B-it-uncensored";

/**
 * Reasoning level values compatible with Vercel AI SDK v4.
 *
 * Maps to `chat_template_kwargs.enable_thinking` in llama.cpp.
 * Only `'none'` disables thinking; all other levels enable it.
 */
export type LlamaCppReasoningLevel =
  | "provider-default"
  | "none"
  | "minimal"
  | "low"
  | "medium"
  | "high"
  | "xhigh";

/**
 * Base error for llama.cpp provider failures.
 *
 * @example
 * ```ts
 * throw new LlamaCppError('Connection refused', err);
 * ```
 */
export class LlamaCppError extends Error {
  constructor(
    message: string,
    public readonly cause?: unknown,
  ) {
    super(message);
    this.name = "LlamaCppError";
  }
}

/**
 * Thrown when a llama.cpp response field cannot be parsed.
 *
 * Includes the problematic field name and its raw value for debugging.
 *
 * @example
 * ```ts
 * throw new LlamaCppParsingError('Invalid tool call', 'tool_calls', rawValue);
 * ```
 */
export class LlamaCppParsingError extends LlamaCppError {
  constructor(
    message: string,
    public readonly fieldName: string,
    public readonly fieldValue: unknown,
    cause?: unknown,
  ) {
    super(message, cause);
    this.name = "LlamaCppParsingError";
  }
}
